/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ADivisaoExpMultiplicative extends PExpMultiplicative
{
    private PExpMultiplicative _expMultiplicative_;
    private TDivisao _divisao_;
    private PExpUnary _expUnary_;

    public ADivisaoExpMultiplicative()
    {
        // Constructor
    }

    public ADivisaoExpMultiplicative(
        @SuppressWarnings("hiding") PExpMultiplicative _expMultiplicative_,
        @SuppressWarnings("hiding") TDivisao _divisao_,
        @SuppressWarnings("hiding") PExpUnary _expUnary_)
    {
        // Constructor
        setExpMultiplicative(_expMultiplicative_);

        setDivisao(_divisao_);

        setExpUnary(_expUnary_);

    }

    @Override
    public Object clone()
    {
        return new ADivisaoExpMultiplicative(
            cloneNode(this._expMultiplicative_),
            cloneNode(this._divisao_),
            cloneNode(this._expUnary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivisaoExpMultiplicative(this);
    }

    public PExpMultiplicative getExpMultiplicative()
    {
        return this._expMultiplicative_;
    }

    public void setExpMultiplicative(PExpMultiplicative node)
    {
        if(this._expMultiplicative_ != null)
        {
            this._expMultiplicative_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultiplicative_ = node;
    }

    public TDivisao getDivisao()
    {
        return this._divisao_;
    }

    public void setDivisao(TDivisao node)
    {
        if(this._divisao_ != null)
        {
            this._divisao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divisao_ = node;
    }

    public PExpUnary getExpUnary()
    {
        return this._expUnary_;
    }

    public void setExpUnary(PExpUnary node)
    {
        if(this._expUnary_ != null)
        {
            this._expUnary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMultiplicative_)
            + toString(this._divisao_)
            + toString(this._expUnary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMultiplicative_ == child)
        {
            this._expMultiplicative_ = null;
            return;
        }

        if(this._divisao_ == child)
        {
            this._divisao_ = null;
            return;
        }

        if(this._expUnary_ == child)
        {
            this._expUnary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMultiplicative_ == oldChild)
        {
            setExpMultiplicative((PExpMultiplicative) newChild);
            return;
        }

        if(this._divisao_ == oldChild)
        {
            setDivisao((TDivisao) newChild);
            return;
        }

        if(this._expUnary_ == oldChild)
        {
            setExpUnary((PExpUnary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
