/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEConditionalOr extends PConditionalOr
{
    private PConditionalAnd _conditionalAnd_;

    public AEConditionalOr()
    {
        // Constructor
    }

    public AEConditionalOr(
        @SuppressWarnings("hiding") PConditionalAnd _conditionalAnd_)
    {
        // Constructor
        setConditionalAnd(_conditionalAnd_);

    }

    @Override
    public Object clone()
    {
        return new AEConditionalOr(
            cloneNode(this._conditionalAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEConditionalOr(this);
    }

    public PConditionalAnd getConditionalAnd()
    {
        return this._conditionalAnd_;
    }

    public void setConditionalAnd(PConditionalAnd node)
    {
        if(this._conditionalAnd_ != null)
        {
            this._conditionalAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionalAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionalAnd_ == child)
        {
            this._conditionalAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionalAnd_ == oldChild)
        {
            setConditionalAnd((PConditionalAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
