/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFactorLogicTermlogic extends PTermlogic
{
    private PFactorlogic _factorlogic_;

    public AFactorLogicTermlogic()
    {
        // Constructor
    }

    public AFactorLogicTermlogic(
        @SuppressWarnings("hiding") PFactorlogic _factorlogic_)
    {
        // Constructor
        setFactorlogic(_factorlogic_);

    }

    @Override
    public Object clone()
    {
        return new AFactorLogicTermlogic(
            cloneNode(this._factorlogic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFactorLogicTermlogic(this);
    }

    public PFactorlogic getFactorlogic()
    {
        return this._factorlogic_;
    }

    public void setFactorlogic(PFactorlogic node)
    {
        if(this._factorlogic_ != null)
        {
            this._factorlogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factorlogic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factorlogic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factorlogic_ == child)
        {
            this._factorlogic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factorlogic_ == oldChild)
        {
            setFactorlogic((PFactorlogic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
