/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AForCommand extends PCommand
{
    private TNInt _x1_;
    private TNInt _x2_;
    private final LinkedList<PCommand> _command_ = new LinkedList<PCommand>();

    public AForCommand()
    {
        // Constructor
    }

    public AForCommand(
        @SuppressWarnings("hiding") TNInt _x1_,
        @SuppressWarnings("hiding") TNInt _x2_,
        @SuppressWarnings("hiding") List<?> _command_)
    {
        // Constructor
        setX1(_x1_);

        setX2(_x2_);

        setCommand(_command_);

    }

    @Override
    public Object clone()
    {
        return new AForCommand(
            cloneNode(this._x1_),
            cloneNode(this._x2_),
            cloneList(this._command_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForCommand(this);
    }

    public TNInt getX1()
    {
        return this._x1_;
    }

    public void setX1(TNInt node)
    {
        if(this._x1_ != null)
        {
            this._x1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x1_ = node;
    }

    public TNInt getX2()
    {
        return this._x2_;
    }

    public void setX2(TNInt node)
    {
        if(this._x2_ != null)
        {
            this._x2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x2_ = node;
    }

    public LinkedList<PCommand> getCommand()
    {
        return this._command_;
    }

    public void setCommand(List<?> list)
    {
        for(PCommand e : this._command_)
        {
            e.parent(null);
        }
        this._command_.clear();

        for(Object obj_e : list)
        {
            PCommand e = (PCommand) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._command_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._x1_)
            + toString(this._x2_)
            + toString(this._command_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._x1_ == child)
        {
            this._x1_ = null;
            return;
        }

        if(this._x2_ == child)
        {
            this._x2_ = null;
            return;
        }

        if(this._command_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._x1_ == oldChild)
        {
            setX1((TNInt) newChild);
            return;
        }

        if(this._x2_ == oldChild)
        {
            setX2((TNInt) newChild);
            return;
        }

        for(ListIterator<PCommand> i = this._command_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCommand) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
