/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIdArrayVar extends PVar
{
    private TIdArray _idArray_;

    public AIdArrayVar()
    {
        // Constructor
    }

    public AIdArrayVar(
        @SuppressWarnings("hiding") TIdArray _idArray_)
    {
        // Constructor
        setIdArray(_idArray_);

    }

    @Override
    public Object clone()
    {
        return new AIdArrayVar(
            cloneNode(this._idArray_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdArrayVar(this);
    }

    public TIdArray getIdArray()
    {
        return this._idArray_;
    }

    public void setIdArray(TIdArray node)
    {
        if(this._idArray_ != null)
        {
            this._idArray_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idArray_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idArray_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idArray_ == child)
        {
            this._idArray_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idArray_ == oldChild)
        {
            setIdArray((TIdArray) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
