/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ALogicFactor extends PFactor
{
    private PExplogic _explogic_;

    public ALogicFactor()
    {
        // Constructor
    }

    public ALogicFactor(
        @SuppressWarnings("hiding") PExplogic _explogic_)
    {
        // Constructor
        setExplogic(_explogic_);

    }

    @Override
    public Object clone()
    {
        return new ALogicFactor(
            cloneNode(this._explogic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicFactor(this);
    }

    public PExplogic getExplogic()
    {
        return this._explogic_;
    }

    public void setExplogic(PExplogic node)
    {
        if(this._explogic_ != null)
        {
            this._explogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogic_ == child)
        {
            this._explogic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogic_ == oldChild)
        {
            setExplogic((PExplogic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
