/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANegativoExpUnary extends PExpUnary
{
    private TMenos _menos_;
    private PExpUnary _expUnary_;

    public ANegativoExpUnary()
    {
        // Constructor
    }

    public ANegativoExpUnary(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExpUnary _expUnary_)
    {
        // Constructor
        setMenos(_menos_);

        setExpUnary(_expUnary_);

    }

    @Override
    public Object clone()
    {
        return new ANegativoExpUnary(
            cloneNode(this._menos_),
            cloneNode(this._expUnary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegativoExpUnary(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExpUnary getExpUnary()
    {
        return this._expUnary_;
    }

    public void setExpUnary(PExpUnary node)
    {
        if(this._expUnary_ != null)
        {
            this._expUnary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._expUnary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._expUnary_ == child)
        {
            this._expUnary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._expUnary_ == oldChild)
        {
            setExpUnary((PExpUnary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
