/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASubtracaoExpAdditive extends PExpAdditive
{
    private PExpAdditive _expAdditive_;
    private TMenos _menos_;
    private PExpMultiplicative _expMultiplicative_;

    public ASubtracaoExpAdditive()
    {
        // Constructor
    }

    public ASubtracaoExpAdditive(
        @SuppressWarnings("hiding") PExpAdditive _expAdditive_,
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExpMultiplicative _expMultiplicative_)
    {
        // Constructor
        setExpAdditive(_expAdditive_);

        setMenos(_menos_);

        setExpMultiplicative(_expMultiplicative_);

    }

    @Override
    public Object clone()
    {
        return new ASubtracaoExpAdditive(
            cloneNode(this._expAdditive_),
            cloneNode(this._menos_),
            cloneNode(this._expMultiplicative_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtracaoExpAdditive(this);
    }

    public PExpAdditive getExpAdditive()
    {
        return this._expAdditive_;
    }

    public void setExpAdditive(PExpAdditive node)
    {
        if(this._expAdditive_ != null)
        {
            this._expAdditive_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAdditive_ = node;
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExpMultiplicative getExpMultiplicative()
    {
        return this._expMultiplicative_;
    }

    public void setExpMultiplicative(PExpMultiplicative node)
    {
        if(this._expMultiplicative_ != null)
        {
            this._expMultiplicative_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultiplicative_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAdditive_)
            + toString(this._menos_)
            + toString(this._expMultiplicative_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAdditive_ == child)
        {
            this._expAdditive_ = null;
            return;
        }

        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._expMultiplicative_ == child)
        {
            this._expMultiplicative_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAdditive_ == oldChild)
        {
            setExpAdditive((PExpAdditive) newChild);
            return;
        }

        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._expMultiplicative_ == oldChild)
        {
            setExpMultiplicative((PExpMultiplicative) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
