/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ATermLogicExplogic extends PExplogic
{
    private PTermlogic _termlogic_;

    public ATermLogicExplogic()
    {
        // Constructor
    }

    public ATermLogicExplogic(
        @SuppressWarnings("hiding") PTermlogic _termlogic_)
    {
        // Constructor
        setTermlogic(_termlogic_);

    }

    @Override
    public Object clone()
    {
        return new ATermLogicExplogic(
            cloneNode(this._termlogic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermLogicExplogic(this);
    }

    public PTermlogic getTermlogic()
    {
        return this._termlogic_;
    }

    public void setTermlogic(PTermlogic node)
    {
        if(this._termlogic_ != null)
        {
            this._termlogic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termlogic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termlogic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termlogic_ == child)
        {
            this._termlogic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termlogic_ == oldChild)
        {
            setTermlogic((PTermlogic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
