/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnarioExpMultiplicative extends PExpMultiplicative
{
    private PExpUnary _expUnary_;

    public AUnarioExpMultiplicative()
    {
        // Constructor
    }

    public AUnarioExpMultiplicative(
        @SuppressWarnings("hiding") PExpUnary _expUnary_)
    {
        // Constructor
        setExpUnary(_expUnary_);

    }

    @Override
    public Object clone()
    {
        return new AUnarioExpMultiplicative(
            cloneNode(this._expUnary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnarioExpMultiplicative(this);
    }

    public PExpUnary getExpUnary()
    {
        return this._expUnary_;
    }

    public void setExpUnary(PExpUnary node)
    {
        if(this._expUnary_ != null)
        {
            this._expUnary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expUnary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expUnary_ == child)
        {
            this._expUnary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expUnary_ == oldChild)
        {
            setExpUnary((PExpUnary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
