/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AXorConditionalAnd extends PConditionalAnd
{
    private PConditionalXor _conditionalXor_;

    public AXorConditionalAnd()
    {
        // Constructor
    }

    public AXorConditionalAnd(
        @SuppressWarnings("hiding") PConditionalXor _conditionalXor_)
    {
        // Constructor
        setConditionalXor(_conditionalXor_);

    }

    @Override
    public Object clone()
    {
        return new AXorConditionalAnd(
            cloneNode(this._conditionalXor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXorConditionalAnd(this);
    }

    public PConditionalXor getConditionalXor()
    {
        return this._conditionalXor_;
    }

    public void setConditionalXor(PConditionalXor node)
    {
        if(this._conditionalXor_ != null)
        {
            this._conditionalXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalXor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionalXor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionalXor_ == child)
        {
            this._conditionalXor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionalXor_ == oldChild)
        {
            setConditionalXor((PConditionalXor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
