/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AXorConditionalXor extends PConditionalXor
{
    private PConditionalXor _conditionalXor_;
    private TXor _xor_;
    private PExpEquality _expEquality_;

    public AXorConditionalXor()
    {
        // Constructor
    }

    public AXorConditionalXor(
        @SuppressWarnings("hiding") PConditionalXor _conditionalXor_,
        @SuppressWarnings("hiding") TXor _xor_,
        @SuppressWarnings("hiding") PExpEquality _expEquality_)
    {
        // Constructor
        setConditionalXor(_conditionalXor_);

        setXor(_xor_);

        setExpEquality(_expEquality_);

    }

    @Override
    public Object clone()
    {
        return new AXorConditionalXor(
            cloneNode(this._conditionalXor_),
            cloneNode(this._xor_),
            cloneNode(this._expEquality_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXorConditionalXor(this);
    }

    public PConditionalXor getConditionalXor()
    {
        return this._conditionalXor_;
    }

    public void setConditionalXor(PConditionalXor node)
    {
        if(this._conditionalXor_ != null)
        {
            this._conditionalXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditionalXor_ = node;
    }

    public TXor getXor()
    {
        return this._xor_;
    }

    public void setXor(TXor node)
    {
        if(this._xor_ != null)
        {
            this._xor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xor_ = node;
    }

    public PExpEquality getExpEquality()
    {
        return this._expEquality_;
    }

    public void setExpEquality(PExpEquality node)
    {
        if(this._expEquality_ != null)
        {
            this._expEquality_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expEquality_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditionalXor_)
            + toString(this._xor_)
            + toString(this._expEquality_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditionalXor_ == child)
        {
            this._conditionalXor_ = null;
            return;
        }

        if(this._xor_ == child)
        {
            this._xor_ = null;
            return;
        }

        if(this._expEquality_ == child)
        {
            this._expEquality_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditionalXor_ == oldChild)
        {
            setConditionalXor((PConditionalXor) newChild);
            return;
        }

        if(this._xor_ == oldChild)
        {
            setXor((TXor) newChild);
            return;
        }

        if(this._expEquality_ == oldChild)
        {
            setExpEquality((PExpEquality) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
